name: Build coho page
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Install required packages
        run: |
          curl -fsSL https://apt.fury.io/nushell/gpg.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/fury-nushell.gpg
          echo "deb https://apt.fury.io/nushell/ /" | sudo tee /etc/apt/sources.list.d/fury.list
          sudo apt update
          sudo apt install nushell libfuse2

          curl -fsSL https://imagemagick.org/archive/binaries/magick -o magick
          chmod +x magick
          sudo mv magick /usr/bin
      - uses: actions/checkout@v4
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{secrets.ARTIFACT_TOKEN}}
          workflow_conclusion: success
          name: coho.jar
          repo: sockeye-d/coho
          workflow: gradle-artifact.yml
      - run: java -jar cli-all.jar
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
